driver:
  type: "ChromeDriver"
  executable_path: "E:/git/custom/berzelius/bin/chromedriver.exe"
options:
  binary_path: ""
  arguments:
    --lang: "en_EN"
    ignore-certificate-error: ""
    start-maximized: ""
  experimental_options:
    excludeSwitches: ['load-extension', 'enable-automation']
    useAutomationExtension: False
    prefs:
      profile.default_content_settings.popups: 0
      download.prompt_for_download: False
      download.directory_upgrade: False
      download.default_directory: ".cache/download"
      credentials_enable_service: False
      profile.password_manager_enabled: False
